### ISSUE TITLE
error when run train_base.sh

### ISSUE THREAD

**Issue by xwjim** [SALT-NLP/Structure-Aware-BART#10]
when i run './train_base.sh'. I got the following error. Do you have any idea?

Traceback (most recent call last):
  File "train.py", line 543, in <module>
    main(args)
  File "train.py", line 523, in main
    trainer.test()
  File "/home/wxu/anaconda3/envs/bart/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 712, in test
    results = self.__test_using_best_weights(ckpt_path, test_dataloaders)
  File "/home/wxu/anaconda3/envs/bart/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 724, in __test_using_best_weights
    'ckpt_path is "best", but ModelCheckpoint is not configured to save the best model.'
pytorch_lightning.utilities.exceptions.MisconfigurationException: ckpt_path is "best", but ModelCheckpoint is not configured to save the best model.

**Comment by jiaaoc** [comment]
I did not encounter this issue before. It might be related to some path settings? Might need to check the pytorch-lightning documents.
