### ISSUE TITLE
Error when loading data

### ISSUE THREAD

**Issue by muggin** [SALT-NLP/Structure-Aware-BART#2]
Bash script `train_base.sh` throws the following error:

`Global seed set to 42
Traceback (most recent call last):
File "train.py", line 540, in <module>
main(args)
File "train.py", line 502, in main
checkpoint_callback=get_checkpoint_callback(
File "/export/home/dialogue-sum/sa-bart/src/callbacks.py", line 100, in get_checkpoint_callback
checkpoint_callback = ModelCheckpoint(
TypeError: __init__() got an unexpected keyword argument 'filepath'`

Could be caused by an inconsistent `pytorch_lightning` version. 
The README does not specify which version the authors used.

**Comment by muggin** [comment]
Another error when setting up the model:

`Traceback (most recent call last):
  File "train.py", line 540, in <module>
    main(args)
  File "train.py", line 498, in main
    trainer: pl.Trainer = generic_train(
  File "/export/home/dialogue-sum/sa-bart/src/lightning_base.py", line 689, in generic_train
    trainer = pl.Trainer.from_argparse_args(
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/properties.py", line 212, in from_argparse_args
    return from_argparse_args(cls, args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/argparse.py", line 53, in from_argparse_args
    return cls(**trainer_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 40, in insert_env_defaults
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'early_stop_callback'`


Seems to be a version problem, can you please specify the version of pytorch_lightining you used, or even better create a requirements.txt file?

**Comment by jiaaoc** [comment]
The version of pytorch_lightening I used should be 0.9.0.
